### ISSUE TITLE
剪枝完，微调训练后的无法转换格式（如pytorchscript格式“x.ptl”）

### ISSUE THREAD

**Issue by zxsitu** [ZJU-lishuang/yolov5-v4#3]
作者大大您好，我想把剪枝完，并且微调后的模型导出其他格式（如pytorchscript格式“x.ptl”），使用export.py文件进行导出，结果报错了，请问怎么解决呢？
```
PS F:\PycharmProjects\pythonProject4\yolov5-v4> python export.py --weights test-models/prune0.7/weights/prune_0.7_sewer-yolov5s-sparsity0-last_finetune-best.pt --img-size 640 640 --batch-size 1
Namespace(batch_size=1, img_size=[640, 640], weights='test-models/prune0.7/weights/prune_0.7_sewer-yolov5s-sparsity0-last_finetune-best.pt')
Traceback (most recent call last):
  File "export.py", line 37, in <module>
    gs = int(max(model.stride))  # grid size (max stride)
  File "D:\Anaconda3\envs\yolo_env\lib\site-packages\torch\nn\modules\module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'Darknet' object has no attribute 'stride'
```

**Comment by gmt710** [comment]
有一些后面芯片不可转换的层怎么替换呢？
